server:
  shutdown: graceful

testServer:
  app:
    ip: 192.168.158.107
  database:
    ip: 192.168.158.108

spring:

  boot:
    admin:
      client:
        url:
          - http://${testServer.app.ip}:7700
        username: root
        password: corelife3134

  lifecycle:
    timeout-per-shutdown-phase: 1m

eureka:
  instance:
    preferIpAddress: true
    hostname: registry-service
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://registry-service:8761/eureka


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

