server:
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 1m

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always