server:
  port: 8089

spring:
  application:
    name: uaa-service

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${testServer.database.ip}:5432/uaa-service
    username: postgres
    password: root
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

rabbitmq:
  host: 192.168.158.47
  port: 5672
  username: admin
  password: qazwsx123

sms:
  in-server:
    url: http://10.7.4.205:8572/api/v1/message/send
  out-server:
    url: http://195.158.4.138:8572/api/v1/message/send


swagger:
  endpoint:
    host: ${testServer.app.ip}:8080
    url: /api/auth-service
