server:
  port: 8080

spring:
  application:
    name: gateway-service-dev

  cloud:
    loadbalancer:
      ribbon:
        enabled: false

    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/dev/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s
      routes:
        - id: uaa-service-dev
          uri: lb://uaa-service-dev
          predicates:
            - Path=/dev/auth-service/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: uaa-service-dev
                fallbackuri: forward:/uaaServiceFallBack

        - id: client-service-dev
          uri: lb://client-service-dev
          predicates:
            - Path=/api/client-service/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: client-service-dev
                fallbackuri: forward:/clientServiceFallBack

        - id: swagger-service
          uri: lb://swagger-service
          predicates:
            - Path=/api/swagger-service/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: swagger-service
                fallbackuri: forward:/swaggerServiceFallBack

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000