server:
  port: 8080

spring:
  application:
    name: GATEWAY-SERVICE-DEV

  cloud:
    loadbalancer:
      ribbon:
        enabled: false

    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/dev/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s
      routes:
        - id: UAA-SERVICE
          uri: lb://UAA-SERVICE
          predicates:
            - Path=/api/auth-service/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: UAA-SERVICE
                fallbackuri: forward:/uaaServiceFallBack

        - id: CLIENT-SERVICE
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/api/client-service/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: CLIENT-SERVICE
                fallbackuri: forward:/clientServiceFallBack

        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/product-service/**
          filters:
            - StripPrefix=2
            - name: CircuitBreaker
              args:
                name: PRODUCT-SERVICE
                fallbackuri: forward:/productServiceFallBack

        - id: SWAGGER-SERVICE
          uri: lb://SWAGGER-SERVICE
          predicates:
            - Path=/api/swagger-service/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: SWAGGER-SERVICE
                fallbackuri: forward:/swaggerServiceFallBack

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000